### ISSUE TITLE
Issue with Release 3.5.0

### ISSUE THREAD

**Issue by techwes** [plaid/react-plaid-link#324]
My company had our dependency for react-plaid-link set to `^3.2.0` and today after the release of version 3.5.0 on a new deploy we started to get the following error:
```
Oct 13 22:09:43 ip-172-31-2-133 web: Error: Cannot find module '/var/app/current/node_modules/react-plaid-link/dist/index.js'. Please verify that the package.json has a valid "main" entry
Oct 13 22:09:43 ip-172-31-2-133 web: at tryPackage (node:internal/modules/cjs/loader:427:19)
Oct 13 22:09:43 ip-172-31-2-133 web: at Function.Module._findPath (node:internal/modules/cjs/loader:640:18)
Oct 13 22:09:43 ip-172-31-2-133 web: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
Oct 13 22:09:43 ip-172-31-2-133 web: at Function.Module._load (node:internal/modules/cjs/loader:873:27)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module.require (node:internal/modules/cjs/loader:1100:19)
Oct 13 22:09:43 ip-172-31-2-133 web: at require (node:internal/modules/cjs/helpers:119:18)
Oct 13 22:09:43 ip-172-31-2-133 web: at Object.<anonymous> (/var/app/current/dist/<redacted>.js:14:23)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module._compile (node:internal/modules/cjs/loader:1198:14)
Oct 13 22:09:43 ip-172-31-2-133 web: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module.load (node:internal/modules/cjs/loader:1076:32)
Oct 13 22:09:43 ip-172-31-2-133 web: at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module.require (node:internal/modules/cjs/loader:1100:19)
Oct 13 22:09:43 ip-172-31-2-133 web: at require (node:internal/modules/cjs/helpers:119:18)
Oct 13 22:09:43 ip-172-31-2-133 web: at Object.<anonymous> (/var/app/current/dist/<redacted>.js:14:72)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module._compile (node:internal/modules/cjs/loader:1198:14)
Oct 13 22:09:43 ip-172-31-2-133 web: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module.load (node:internal/modules/cjs/loader:1076:32)
Oct 13 22:09:43 ip-172-31-2-133 web: at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module.require (node:internal/modules/cjs/loader:1100:19)
Oct 13 22:09:43 ip-172-31-2-133 web: at require (node:internal/modules/cjs/helpers:119:18)
Oct 13 22:09:43 ip-172-31-2-133 web: at Object.<anonymous> (/var/app/current/dist/<redacted>.js:8:72)
Oct 13 22:09:43 ip-172-31-2-133 web: at Module._compile (node:internal/modules/cjs/loader:1198:14) {
Oct 13 22:09:43 ip-172-31-2-133 web: code: 'MODULE_NOT_FOUND',
Oct 13 22:09:43 ip-172-31-2-133 web: path: '/var/app/current/node_modules/react-plaid-link/package.json',
Oct 13 22:09:43 ip-172-31-2-133 web: requestPath: 'react-plaid-link'
Oct 13 22:09:43 ip-172-31-2-133 web: }
Oct 13 22:09:43 ip-172-31-2-133 web: > mayflower-website@0.0.0 start-prod
Oct 13 22:09:43 ip-172-31-2-133 web: > NODE_ENV=production node dist/server/server.js
Oct 13 22:09:46 ip-172-31-2-133 web: node:internal/modules/cjs/loader:435
Oct 13 22:09:46 ip-172-31-2-133 web: throw err;
Oct 13 22:09:46 ip-172-31-2-133 web: ^
```
This was with no other changes and the issue was resolved by changing the version in our package.json to `~3.4.0`

**Comment by tzha-plaid** [comment]
We're aware of a build issue with 3.5.0, could you upgrade to 3.5.1? Let us know if you're still having trouble after upgrading to 3.5.1.
